# Vault provides:
# - ANSATTPORTEN_CLIENT_ID
# - ANSATTPORTEN_CLIENT_SECRET

ANSATTPORTEN_API_BASE_URL: https://test.ansattporten.no
ANSATTPORTEN_LOGIN_BASE_URL: https://login.test.ansattporten.no
SIMPLIFIED_ONBOARDING_FRONTEND_URL: https://onboarding.test.maskinporten.no

maskinporten-config:
  - environment: test
    api: https://api.test.samarbeid.digdir.no
    authorization-server: https://test.maskinporten.no

spring:
  application:
    environment: test
