# Vault provides:
# - ANSATTPORTEN_CLIENT_ID
# - ANSATTPORTEN_CLIENT_SECRET

ANSATTPORTEN_API_BASE_URL: https://ansattporten.no
ANSATTPORTEN_LOGIN_BASE_URL: https://login.ansattporten.no
MASKINPORTEN_API_URL: https://integrasjon.difi.no

ENV1: test
ENV1_MASKINPORTEN_API_URL: https://api.test.samarbeid.digdir.no
ENV1_AUTH_SERVER: https://api.test.samarbeid.digdir.no
ENV2: prod
ENV2_MASKINPORTEN_API_URL: https://integrasjon.difi.no
ENV2_AUTH_SERVER: https://maskinporten.no
SIMPLIFIED_ONBOARDING_FRONTEND_URL: https://onboarding.maskinporten.no

spring:
  application:
    environment: prod
