# Vault provides:
# - ANSATTPORTEN_CLIENT_ID
# - ANSATTPORTEN_CLIENT_SECRET

ANSATTPORTEN_API_BASE_URL: https://ansattporten.no
ANSATTPORTEN_LOGIN_BASE_URL: https://login.ansattporten.no
SIMPLIFIED_ONBOARDING_FRONTEND_URL: https://onboarding.maskinporten.no

maskinporten-config:
  - environment: test
    api: https://api.test.samarbeid.digdir.no
    authorization-server: https://test.maskinporten.no
  - environment: prod
    api: https://api.samarbeid.digdir.no
    authorization-server: https://maskinporten.no

spring:
  application:
    environment: prod
