# Vault provides:
# - ANSATTPORTEN_CLIENT_ID
# - ANSATTPORTEN_CLIENT_SECRET

ANSATTPORTEN_API_BASE_URL: https://ansattporten.dev
ANSATTPORTEN_LOGIN_BASE_URL: https://login.ansattporten.dev
SIMPLIFIED_ONBOARDING_FRONTEND_URL: https://onboarding.maskinporten.dev

maskinporten-config:
  - environment: dev
    api: https://serviceprovider-api.apps.eid-systest.norwayeast.aroapp.io
    authorization-server: https://maskinporten.dev

spring:
  application:
    environment: systest

management:
  endpoint:
    health:
      show-details: always
      show-components: always
