# Vault provides:
# - ANSATTPORTEN_CLIENT_ID
# - ANSATTPORTEN_CLIENT_SECRET

ANSATTPORTEN_API_BASE_URL: https://test.ansattporten.no
ANSATTPORTEN_LOGIN_BASE_URL: https://login.test.ansattporten.no
MASKINPORTEN_API_URL: https://integrasjon-ver2.difi.no

ENV1: test
ENV1_MASKINPORTEN_API_URL: https://integrasjon-ver2.difi.no
ENV1_AUTH_SERVER: https://integrasjon-ver2.difi.no
ENV2: ver2
ENV2_MASKINPORTEN_API_URL: https://integrasjon-ver2.difi.no
ENV2_AUTH_SERVER: https://ver2.maskinporten.no
SIMPLIFIED_ONBOARDING_FRONTEND_URL: http://localhost:3000


management:
  endpoint:
    health:
      show-details: always
      show-components: always
