# Requires ANSATTPORTEN_CLIENT_SECRET from env vars

ANSATTPORTEN_CLIENT_ID: forenklet_onboarding_dev
ANSATTPORTEN_API_BASE_URL: https://test.ansattporten.no
ANSATTPORTEN_LOGIN_BASE_URL: https://login.test.ansattporten.no
SIMPLIFIED_ONBOARDING_FRONTEND_URL: http://localhost:3000

maskinporten-config:
  - environment: test
    api: https://api.test.samarbeid.digdir.no
    authorization-server: https://test.maskinporten.no

spring:
  application:
    environment: dev

management:
  endpoint:
    health:
      show-details: always
      show-components: always
