# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and publish Docker image

on:
  push:
    branches: [main]

jobs:
  call-workflow-image-build-publish:
    uses: felleslosninger/github-workflows/.github/workflows/ci-spring-boot-build-publish-image.yml@main
    with:
      java-version: 21
    secrets: inherit

  call-update-image:
    uses: felleslosninger/github-workflows/.github/workflows/ci-call-update-image.yml@main
    needs: call-workflow-image-build-publish
    with:
      application-name: maskinporten-onboarding-backend
      deployment-environment: systest
      image-digest: ${{ needs.call-workflow-image-build-publish.outputs.image-digest }}
      image-name: maskinporten-onboarding-backend
      image-version: ${{ needs.call-workflow-image-build-publish.outputs.image-version }}
      kubernetes-repo: kundetjenester-cd-external
      product-name: onboarding
    secrets: inherit
