# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and publish Docker image

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'src/test/**'
      - 'docker/**'
      - 'docker-compose*.yaml'
      - '*.md'
      - 'LICENSE'

jobs:
  call-workflow-image-build-publish:
    uses: felleslosninger/github-workflows/.github/workflows/ci-spring-boot-build-publish-image.yml@main
    with:
      java-version: 17
    secrets: inherit
  call-update-image-version:
    uses: felleslosninger/github-workflows/.github/workflows/ci-update-image-version.yml@main
    needs: call-workflow-image-build-publish
    with:
      kubernetes-repo: kundetjenester-cd-external
      image-version: ${{ needs.call-workflow-image-build-publish.outputs.image-version }}
      image-digest: ${{ needs.call-workflow-image-build-publish.outputs.image-digest }}
    secrets: inherit
